language: php
php:
- 5.5
before_script:
- curl -s http://getcomposer.org/installer | php
- php composer.phar install --dev --no-interaction
script:
- mkdir -p tests/build/logs
- vendor/bin/phpunit -c ./tests/phpunit.xml
deploy:
  provider: heroku
  api_key:
    secure: pEKOJDMcyYkq2CInXqjrbeeQuOkhLzGY6v6hK1b6EXt1mKXXtU3qUakBreQcva34T7gko6ROYXSQ8MDBXgNKU+/xmX0ZTHwjjNn8MWn6rcHYi9iZtiiTcPh6jeWxCzu7auLU9Znj1N1r9b/Dl4pOB3tmkpAzBRj7goZkw0ANE2g=
  app: moj-opg-48hr-hackathon
  on:
    repo: eddiejaoude/ministryofjustice-opg-48h-hackathon
after_success:
  - make build.package
env:
  global:
    - secure: jA0BeOGANgK2z9Zdx0wEwQ0z7A763Co3UM/TvtQdrzDgBnflBAdfQXRLRHV4DI0wyRnWahxDwGVsRUI2/IimntRj3qk3PMEi2ziDrJbb0bjazjb9WhFrYfNlNB3qAia2GNrbw2qnHgLBV63KNvhd/wzXWePNRk93hrpyJ+tGjj8=
branches:
  except:
    - /^build-[0-9a-z\-]*/
