<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Pinecone Free Dashboard, Metrics and Visualisations ') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/nv.d3.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/nv.d3.min.js')
            ->prependFile($this->basePath() . '/js/d3.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">Pinecone Free</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="disabled"><a href="<?php echo $this->url('home') ?>">v:<?php echo file_get_contents('VERSION'); ?></a></li>
                        <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <li><a href="<?php echo $this->url('database') ?>"><?php echo $this->translate('Database') ?></a></li>
                        <li><a href="<?php echo $this->url('elasticsearch') ?>"><?php echo $this->translate('ElasticSearch') ?></a></li>
                        <li class="disabled"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Queues') ?></a></li>
                        <li class="disabled"><a href="<?php echo $this->url('case') ?>"><?php echo $this->translate('Case') ?></a></li>
                        <li><a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('User') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Pinecone Free Team <?php echo $this->translate('All rights reserved.') ?></p>
                <p class="pull-right">Version: <?php echo file_get_contents('VERSION'); ?></p>
                <ul><?php foreach(file('CHANGELOG') as $log) { echo '<li>' . $log . '</li>'; }; ?></ul>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
