
<h2>User</h2>

<div class="row">

    <form class="form-inline" role="form" method="POST">

        <select class="form-control" name="user_id">
            <?php
            foreach($this->assignees as $assignee) {
            ?>
                <option value="<?php echo $assignee['id']; ?>"><?php echo $assignee['email']; ?></option>
            <?php
            }
            ?>
        </select>

        <select class="form-control" name="range">
            <option value="24">24hrs</option>
            <option value="48">48hrs</option>
        </select>

        <button type="submit" class="btn btn-default">GO</button>
    </form>


</div>

<div class="row">
    <div class="alert alert-info pull-left" role="alert">Total Hours 42</div>
    <div class="alert alert-success pull-left" role="alert">Productivety 4.5</div>

</div>


<div class="row">

    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#">History</a></li>
        <li role="presentation"><a href="#">Future</a></li>
    </ul>

</div>


<div class="row">

    <table class="table table-hover">
        <?php
        foreach($this->taskEvents as $event) {
            ?>
            <tr>
                <td>
                    <?php echo $event['sourceentityclass']; ?>
                </td>
                <td>
                    <?php echo $event['type']; ?>
                </td>
                <td>
                    <?php echo $event['changeset']; ?>
                </td>
                <td>
                    <?php echo print_r($event['entity'], true); ?>
                </td>
            </tr>
        <?php
        }
        ?>
    </table>

</div>