<style>

    #chart svg {
        height: 800px;
    }

    #chart2 svg {
        height: 800px;
    }

</style>


<h2>Database Statistics</h2>

<!--<div id="chart">-->
    <!--<svg></svg>-->
<!--</div>-->

<div id="chart2">
    <svg></svg>
</div>

<table class="table table-hover">
    <thead>
    <tr>
        <td>Table</td>
        <td>Total</td>
        <td>Size (bytes)</td>
    </tr>
    </thead>
    <tbody>
    <?php
            foreach($this->statistics as $tableName=>$stats) {
            ?>
    <tr>
        <td><?php echo $tableName; ?></td>
        <td><?php echo $stats['total']; ?></td>
        <td><?php echo $stats['size']; ?></td>
    </tr>
    <?php
            }
            ?>
    </tbody>
    </table>

<script>

// Pie chart
//nv.addGraph(function() {
//    var chart = nv.models.pieChart()
//            .x(function(d) { return d.label })
//            .y(function(d) { return d.value })
//            .showLabels(true);
//
//    d3.select("#chart svg")
//            .datum(pieSize())
//            .transition().duration(350)
//            .call(chart);
//
//    return chart;
//});

//Donut chart example
nv.addGraph(function() {
    var chart = nv.models.pieChart()
                    .x(function(d) { return d.label })
                    .y(function(d) { return d.value })
                    .showLabels(true)     //Display pie labels
                    .labelThreshold(.05)  //Configure the minimum slice size for labels to show up
                    .labelType("percent") //Configure what type of data to show in the label. Can be "key", "value" or "percent"
                    .donut(true)          //Turn on Donut mode. Makes pie chart look tasty!
                    .donutRatio(0.35)     //Configure how big you want the donut hole size to be.
            ;

    d3.select("#chart2 svg")
            .datum(pieTotal())
            .transition().duration(350)
            .call(chart);

    return chart;
});

//Pie chart example data. Note how there is only a single array of key-value pairs.
function pieTotal() {
    var pieTotal =  <?php echo json_encode($this->pieTotal); ?>;
    return pieTotal;
}

//function pieSize() {

//var pieSize =  <?php echo json_encode($this->pieSize); ?>;

//    return [
//        {
//            label: 'A',
//            value: 1220
//        },
//        {
//            label: 'B',
//            value: 2220
//        },
//        {
//            label: 'C',
//            value: 3220
//        }
//    ];
//}

</script>
