<h2>Database Statistics</h2>

<table class="table table-hover">
    <thead>
    <tr>
        <td>Table</td>
        <td>Total</td>
        <td>Size (bytes)</td>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($this->statistics->getTableNames() as $tableName) {
        var_dump($this->sql->select()->from($tableName)->columns(array('recordCount' => new \Zend\Db\Sql\Expression('COUNT(*)')))); exit;
        ?>
        <tr>
            <td><?php echo $tableName; ?></td>
            <td><?php echo $tableName; ?></td>
            <td><?php echo $tableName; ?></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
