<div class="jumbotron">
    <h1>Welcome to the <span class="zf-green">Pinecone Free Dashboard</span></h1>
    <p>This is the Pinecone Free team system dashboard, providing metrics and visualisations of what is happening under the hood of the application server.</p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/eddiejaoude/ministryofjustice-opg-48h-hackathon" target="_blank">Fork this on GitHub &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Database Statistics</h3>
            </div>
            <div class="panel-body">
                <p>Database statistics</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('database') ?>">Database Statistics &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Elastic Search Statistics</h3>
            </div>
            <div class="panel-body">
                <p>Elastic Search statistics</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('elasticsearch') ?>">Elastic Search Statistics &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Case Overview</h3>
            </div>
            <div class="panel-body">
                <p>Case overview</p>
                <p><a class="btn btn-success pull-right" href="<?php echo $this->url('case') ?>">Case Overview &raquo;</a></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Github Repository</h3>
            </div>
            <div class="panel-body">
                <p>Link to <a href="https://github.com/eddiejaoude/ministryofjustice-opg-48h-hackathon">Github Repository</a></p>
                <p><a class="btn btn-success pull-right" href="https://github.com/eddiejaoude/ministryofjustice-opg-48h-hackathon">Github Repository &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Travis CI Project</h3>
            </div>
            <div class="panel-body">
                <p>Continuous Integration on <a href="https://travis-ci.org/eddiejaoude/ministryofjustice-opg-48h-hackathon">Travis CI project<a/></p>
                <p><a class="btn btn-success pull-right" href="https://travis-ci.org/eddiejaoude/ministryofjustice-opg-48h-hackathon">Travis CI &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Dashboard of Pipeline</h3>
            </div>
            <div class="panel-body">
                <p>Github Commits & Travis CI build status dashboard</p>
                <p><a class="btn btn-success pull-right disabled" href="http://localhost:3030/github-travis">Look at the BIG screen</a></p>
            </div>
        </div>
    </div>
</div>
